name: Build Image
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/gary-jipp/demo-servlet:latest
            ghcr.io/gary-jipp/demo-servlet:${{ github.sha }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      # - name: Build the Docker image
      #   run: |
      #     docker build . -f Dockerfile -t ghcr.io/gary-jipp/demo-servlet:latest

      # - name: Push Docker Image to Container Registry
      #   run: |
      #     docker push ghcr.io/gary-jipp/demo-servlet:latest